### ISSUE TITLE
open telemetry integration

### ISSUE THREAD

**Issue by wirowka** [ibm-messaging/mq-jms-spring#117]
hi All
Is there any way to get OpenTelemetry traces similar to what @ibmmqmet described in:
https://marketaylor.synology.me/?p=1674
from spring?
We do use:
- spring boot 3.2.2
- com.ibm.mq:mq-jms-spring-boot-starter:3.1.2
- java 21
- open telemetry from Elastic (1.1): 
    - opentelemetry-javaagent: [2.10.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.10.0)
    - opentelemetry-sdk: [1.44.1](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.44.1)
    - opentelemetry-semconv: [1.28.0](https://github.com/open-telemetry/semantic-conventions-java/releases/tag/v1.28.0)
    - opentelemetry-java-contrib: [1.40.0](https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.40.0)

The setup works fine for other applications, but JMS connectors we wrote (e.g.: for IBM MQ) using this spring library does not produce anything.

Many thanks in advance for help

**Comment by ibmmqmet** [comment]
The `putget` application used as the config example in that article IS a Spring Boot application which has been built as a fat jar using version 3.3.5 of this starter. 

There's no explicit use of OTel within the app, as it says. Just the `opentelemetry-javagent` at startup which has all the sdk etc embedded.

**Comment by wimdeblauwe-volvo** [comment]
I managed to get traces with these dependencies:

* Spring Boot 3.4.3
* mq-jms-spring-boot-starter: 3.3.5
* Micrometer and opentelemetry dependencies like this:

```
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-otlp</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-otel</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry.instrumentation</groupId>
			<artifactId>opentelemetry-logback-appender-1.0</artifactId>
			<version>2.13.3-alpha</version>
		</dependency>
```

I tested this with a Docker compose that uses `grafana/otel-lgtm`:

```
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=1000
``` 

And these settings in my `application.yml`:

```
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "loggers,info,health,metrics"
  endpoint:
    loggers:
      access: read_only
    info:
      access: read_only
    health:
      access: read_only
    metrics:
      access: read_only
```

And these in `application-local.yml`:

```
management:
  otlp:
    logging:
      endpoint: "http://localhost:4317"
      transport: grpc
    tracing:
      endpoint: "http://localhost:4317"
      transport: grpc
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
```

I did not use the javaagent.
